const puppeteer = require("puppeteer");

const fs = require("fs");
async function crawler(keyword) {
  try {
    const browser = await puppeteer.launch({
      headless: false,
    });
    const page = await browser.newPage();
    await page.setCookie(
      {
        domain: ".tiktok.com",
        hostOnly: false,
        httpOnly: false,
        name: "_abck",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "58A740C14BB7B9CB4974D9E8201832FA~-1~YAAQjqwwF5loFoqDAQAAPjnAjQirBBRT2N1sdBejYNrda3q9cMQhSc2C/zUF4IKffnrngqcl9g64seKuEDcCIMahXrKRNXs8muEMtGPR4+EA4Rd8DGVjl+PlHN/KmQ607AkmCrk+oGCvcEOd0ni5kmQORgV7TVcvBFGdNjJK6jFtC0YR+3VonraknBJeLVj3SgxNuU1Idn8AqXUcMhMxWAeQ6EdRWfP+Ir2o+Kf8N0hk07KSZo8dCcmQQ/H2zb+VUIrfEh46FRKvZdqcZl1sYe6CxEhWvr/PG452Ekc0YtJQrLC8d+BgV4/hLjyeX2zqCH4KG7Wm8xtI/3HkHpNlCYcQ5DxN00DRp6FTOLuAuOz/SxvXkRc4gfY=~-1~-1~-1",
        id: 1,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1664544927.923191,
        hostOnly: false,
        httpOnly: false,
        name: "bm_sz",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "8D296982E8099242D01A1B1C0203BDF1~YAAQjqwwF5poFoqDAQAAPjnAjREjY4sL0AieTgPOHpcioGv04mSXQQ4iW51c6E5jTD1hBQK/fsU1HYKu7ESWqEUqd8SIOTrIeVmuTWJFDLbDFn74uF9sCCIClcLZfSm0kW6Q7MCbOBSOfdwdOuQEaCRr6/reLdZZrQEgBtgsfe1uK5TeUzt1XlbYdG/+L0cZMXJ9yWumA6WZN3rav9cI+tnhlmYGy6MdH27S1+5bDr4ulLB1cghSsKzE1zP5572qPoXJq5HCRKptsXzrxa2/DDkr00A46ejRKapuqVFNG2IBIH0=~3159347~4277315",
        id: 2,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567516,
        hostOnly: false,
        httpOnly: true,
        name: "cmpl_token",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value: "AgQQAPOFF-RO0rMITbRa8x0_-VchZo0C_4MOYMTXKw",
        id: 3,
      },
      {
        domain: ".tiktok.com",
        hostOnly: false,
        httpOnly: false,
        name: "msToken",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "FSWe63ltyS9pecNboLKYOKUJxof_oSDsBKIfKNBetuF4lYiSmCEzFm7fYMBs3umPTKz6eEyX7EGYzG7posZ14OY5f0iAUuIUAHVGMqh-UwW8KyQw7e-YnrKKnyLonw==",
        id: 4,
      },
      {
        domain: ".tiktok.com",
        hostOnly: false,
        httpOnly: true,
        name: "odin_tt",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "887a0c4841dc69cf63a1a7cda62e6aaac39dd5a13b1cc16c6146db726451fe8b538aba37a6b5d2c14c576727e0fa28c42d7cbb23052096ce918e38c2caf662045799749f8c27cc60f0a3c38769a637b3",
        id: 5,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1667122551.567568,
        hostOnly: false,
        httpOnly: true,
        name: "passport_auth_status",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "f1a0d697e29a32ee7961126154c6490a%2C",
        id: 6,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1667122551.567636,
        hostOnly: false,
        httpOnly: true,
        name: "passport_auth_status_ss",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "f1a0d697e29a32ee7961126154c6490a%2C",
        id: 7,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714539.926883,
        hostOnly: false,
        httpOnly: false,
        name: "passport_csrf_token",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "57f9a1b6024bb2e223e0624254e28ae7",
        id: 8,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714539.926975,
        hostOnly: false,
        httpOnly: false,
        name: "passport_csrf_token_default",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "57f9a1b6024bb2e223e0624254e28ae7",
        id: 9,
      },
      {
        domain: ".tiktok.com",
        hostOnly: false,
        httpOnly: false,
        name: "s_v_web_id",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: true,
        storeId: "0",
        value: "verify_l8oai9g5_NxcC8xpa_4uBc_4vXY_8rQ7_APwLyhFaJiLv",
        id: 10,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567895,
        hostOnly: false,
        httpOnly: true,
        name: "sessionid",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "0d831e3613cc7852ebaa611315f2f8ce",
        id: 11,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567943,
        hostOnly: false,
        httpOnly: true,
        name: "sessionid_ss",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value: "0d831e3613cc7852ebaa611315f2f8ce",
        id: 12,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1695634551.567698,
        hostOnly: false,
        httpOnly: true,
        name: "sid_guard",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "0d831e3613cc7852ebaa611315f2f8ce%7C1664530551%7C5184000%7CTue%2C+29-Nov-2022+09%3A35%3A51+GMT",
        id: 13,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567845,
        hostOnly: false,
        httpOnly: true,
        name: "sid_tt",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "0d831e3613cc7852ebaa611315f2f8ce",
        id: 14,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567995,
        hostOnly: false,
        httpOnly: true,
        name: "sid_ucp_v1",
        path: "/",
        sameSite: "unspecified",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "1.0.0-KDBkMTJkZDM4Y2YyM2I2OTZmYWM3N2MwN2VjMjdhN2ZjNzdjNDhjNTUKHwiGiIeWveKom2MQ9_DamQYYswsgDDD28NqZBjgIQBIQAxoGbWFsaXZhIiAwZDgzMWUzNjEzY2M3ODUyZWJhYTYxMTMxNWYyZjhjZQ",
        id: 15,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.56806,
        hostOnly: false,
        httpOnly: true,
        name: "ssid_ucp_v1",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "1.0.0-KDBkMTJkZDM4Y2YyM2I2OTZmYWM3N2MwN2VjMjdhN2ZjNzdjNDhjNTUKHwiGiIeWveKom2MQ9_DamQYYswsgDDD28NqZBjgIQBIQAxoGbWFsaXZhIiAwZDgzMWUzNjEzY2M3ODUyZWJhYTYxMTMxNWYyZjhjZQ",
        id: 16,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.827615,
        hostOnly: false,
        httpOnly: true,
        name: "store-country-code",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "vn",
        id: 17,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.827629,
        hostOnly: false,
        httpOnly: true,
        name: "store-country-code-src",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "uid",
        id: 18,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.827575,
        hostOnly: false,
        httpOnly: true,
        name: "store-idc",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "useast2a",
        id: 19,
      },
      {
        domain: ".tiktok.com",
        hostOnly: false,
        httpOnly: true,
        name: "tt_csrf_token",
        path: "/",
        sameSite: "lax",
        secure: true,
        session: true,
        storeId: "0",
        value: "MZL16OTU-W5DrAxKZ5c5z9PrhJ8Z80f27hP8",
        id: 20,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.827641,
        hostOnly: false,
        httpOnly: true,
        name: "tt-target-idc",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value: "alisg",
        id: 21,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1696066557.375346,
        hostOnly: false,
        httpOnly: true,
        name: "tt-target-idc-sign",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "O5zIc0oCvgjYSwSUmzCH-pvIkekLZcT_q1DjYtQF94gFzecgsw0CjnVddYrS74G80gyhdIr_f0FoG73wEdD1quiEk0XjF-1-MBIxQ6DUe1Ap9-3QFqaIOCs1JmVQnvtYSj3WNucyCpojlsKU4D2N_3ITNrZcwmcAlR85UdQjQJ5Ib89l9YbA8hvSzCh1hckIqRDfzPGH-FhZ4gi7KzHjX_XEhl4lxPhEuyzGDD6u_obyAMPeWh59HI8Zo2m_6fqorVeLui2ZYrScSh7WttlpBwlmHGjrm3ohozTPTyrz4JV7Fwdp6_WmFT2AOpxODyAnsCQhsc3Va5FhWkWe5lA1VzPyX4BWZoiCsECTFQL3Ue_jV9O6dj3ehDmGRoqxxnUxsdSa-XMkOOC9oPdXq2-1VMFTO4EpBOTub16QKq2jZv5pIzhXGCxSXoqfSiFQp9RiV7D-NgsXfqQNPkE6Rc55ynZg43aNRJs-oi-pdy_1MiGsk10SXXavpWjUVFcSTW2S",
        id: 22,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1696066562.007949,
        hostOnly: false,
        httpOnly: true,
        name: "ttwid",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "1%7CyrgTMwa6fibIfpiO-NAiYcG3BSRB3xZP2y7jbLVmw4o%7C1664530561%7Caf750bf3328f9f960f0d8f7efffc2d94894ceb2437f323e7a7b78a2151b9d1b5",
        id: 23,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567748,
        hostOnly: false,
        httpOnly: true,
        name: "uid_tt",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "2da9c978e2c3cafd8b819dec203cb655b288be6239563ccb9a68a0ec756f1919",
        id: 24,
      },
      {
        domain: ".tiktok.com",
        expirationDate: 1669714551.567796,
        hostOnly: false,
        httpOnly: true,
        name: "uid_tt_ss",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: false,
        storeId: "0",
        value:
          "2da9c978e2c3cafd8b819dec203cb655b288be6239563ccb9a68a0ec756f1919",
        id: 25,
      },
      {
        domain: ".www.tiktok.com",
        expirationDate: 1665135361,
        hostOnly: false,
        httpOnly: false,
        name: "__tea_cache_tokens_1988",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "{%22_type_%22:%22default%22%2C%22user_unique_id%22:%227149104134289737217%22%2C%22timestamp%22:1664530530235}",
        id: 26,
      },
      {
        domain: ".www.tiktok.com",
        hostOnly: false,
        httpOnly: false,
        name: "passport_fe_beating_status",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: true,
        storeId: "0",
        value: "true",
        id: 27,
      },
      {
        domain: "www.tiktok.com",
        hostOnly: true,
        httpOnly: false,
        name: "csrf_session_id",
        path: "/",
        sameSite: "no_restriction",
        secure: true,
        session: true,
        storeId: "0",
        value: "658e0bd61185e9e33694f31c7a238cc2",
        id: 28,
      },
      {
        domain: "www.tiktok.com",
        expirationDate: 1672306566,
        hostOnly: true,
        httpOnly: false,
        name: "msToken",
        path: "/",
        sameSite: "unspecified",
        secure: false,
        session: false,
        storeId: "0",
        value:
          "FSWe63ltyS9pecNboLKYOKUJxof_oSDsBKIfKNBetuF4lYiSmCEzFm7fYMBs3umPTKz6eEyX7EGYzG7posZ14OY5f0iAUuIUAHVGMqh-UwW8KyQw7e-YnrKKnyLonw==",
        id: 29,
      }
    );
    await page.goto("https://www.tiktok.com/");

    var index = 0;
    var result = [];
    var len = 0;

    while (index < 1000) {
      await page.goto(
        `https://www.tiktok.com/api/search/general/full/?aid=1988&app_language=en&app_name=tiktok_web&battery_info=1&browser_language=en-US&browser_name=Mozilla&browser_online=true&browser_platform=MacIntel&browser_version=5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_7%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F109.0.0.0%20Safari%2F537.36&channel=tiktok_web&cookie_enabled=true&device_id=7195847471703033345&device_platform=web_pc&focus_state=true&from_page=search&is_fullscreen=false&is_page_visible=true&keyword=${keyword}&offset=${
          index * 12
        }&os=mac&priority_region=&referer=&region=VN&screen_height=900&screen_width=1440&tz_name=Asia%2FSaigon&webcast_language=en&msToken=onquUjM7mZ3SvtWD_IvPeNIm8sezqsTNmGpynsYXCfxn_muy3Sq7Puh90W7vN3ithiob31puSdm2s49ZjzALk73HHY0v2baYRIAR455dlpEOo50LK8XIB5RcIpxwZ33csKiofUnN2Wzbk5VyVw==&X-Bogus=DFSzswVLaBsANtfTShgPqRAeCxYm&_signature=_02B4Z6wo00001lCCVZgAAIDDOA4aAruwYT5QglEAAPfUf0`,
        { waitUntil: "networkidle0" }
      );
      index += 1;
      const text = await page.$eval("body > pre", (el) => el.textContent);
      console.log("index " + index + " ");
      const textRes = JSON.parse(text);
      if (textRes.status_code == 0) break;
      const res = textRes.data
        .filter((item) => item.type == 1)
        .map((item) => {
          return {
            createTime: item.item.createTime,
            link: `https://www.tiktok.com/@${item.item.author.uniqueId}/video/${item.item.id}`,
          };
        });
      result = result.concat(res);
      len += res.length;
    }
    fs.writeFileSync(
      `${keyword}-${len}-${Date.now()}.json`,
      JSON.stringify(result)
    );
    await browser.close();
  } catch (error) {
    console.log(error);
  }
}

const keywords = ["facebook", "youtube", "tiktok"];
keywords.forEach((item) => {
  crawler(item);
});
